FROM node:16

# Install Dependencies
COPY package*.json ./
RUN npm install

# Copy source code into the image
COPY . .

RUN npm install

# Exports
EXPOSE 3000

# Run back-end when container launch
CMD ["nodemon","server.js"]